import * as t from 'babel-types'
import genAttributeTypeAnnotation from "./genAttributeTypeAnnotation"

export default function genAttributeObjectTypeProperty(attribute, options = {}) {
  const property = t.objectTypeProperty(
    t.identifier(attribute.fieldName),
    genAttributeTypeAnnotation(attribute)
  )
  property.optional = attribute.allowNull !== false || Boolean(options.forInitializer && attribute._autoGenerated)
  return property
}

